In [1]:
from selenium import webdriver

In [2]:
import pandas as pd

In [3]:
options = webdriver.ChromeOptions()

In [4]:
options.add_argument("--incognito")

In [5]:
driver = webdriver.Chrome("./chromedriver.exe", options=options)

## Récupérer le nom des joueurs et leur âge par saison

In [6]:
driver.get("https://fbref.com/en/squads/822bd0ba/2012-2013/Liverpool-Stats")
element = driver.find_elements_by_xpath('//div[@id = "div_stats_standard_602"] //tbody //th[@data-append-csv]')
lst_players2012_2013 = [x.text for x in element]
element = driver.find_elements_by_xpath('//div[@id = "div_stats_standard_602"] //tbody //td[@data-stat = "age"]')
lst_age2012_2013 = [x.text for x in element]

In [7]:
driver.get("https://fbref.com/en/squads/822bd0ba/2013-2014/Liverpool-Stats")
element = driver.find_elements_by_xpath('//div[@id = "div_stats_standard_669"] //tbody //th[@data-append-csv]')
lst_players2013_2014 = [x.text for x in element]
element = driver.find_elements_by_xpath('//div[@id = "div_stats_standard_669"] //tbody //td[@data-stat = "age"]')
lst_age2013_2014 = [x.text for x in element]

In [8]:
driver.get("https://fbref.com/en/squads/822bd0ba/2014-2015/Liverpool-Stats")
element = driver.find_elements_by_xpath('//div[@id = "div_stats_standard_733"] //tbody //th[@data-append-csv]')
lst_players2014_2015 = [x.text for x in element]
element = driver.find_elements_by_xpath('//div[@id = "div_stats_standard_733"] //tbody //td[@data-stat = "age"]')
lst_age2014_2015 = [x.text for x in element]

In [9]:
driver.get("https://fbref.com/en/squads/822bd0ba/2015-2016/Liverpool-Stats")
element = driver.find_elements_by_xpath('//div[@id = "div_stats_standard_1467"] //tbody //th[@data-append-csv]')
lst_players2015_2016 = [x.text for x in element]
element = driver.find_elements_by_xpath('//div[@id = "div_stats_standard_1467"] //tbody //td[@data-stat = "age"]')
lst_age2015_2016 = [x.text for x in element]

In [10]:
driver.get("https://fbref.com/en/squads/822bd0ba/2016-2017/Liverpool-Stats")
element = driver.find_elements_by_xpath('//div[@id = "div_stats_standard_1526"] //tbody //th[@data-append-csv]')
lst_players2016_2017 = [x.text for x in element]
element = driver.find_elements_by_xpath('//div[@id = "div_stats_standard_1526"] //tbody //td[@data-stat = "age"]')
lst_age2016_2017 = [x.text for x in element]

In [11]:
driver.get("https://fbref.com/en/squads/822bd0ba/2017-2018/Liverpool-Stats")
element = driver.find_elements_by_xpath('//div[@id = "div_stats_standard_1631"] //tbody //th[@data-append-csv]')
lst_players2017_2018 = [x.text for x in element]
element = driver.find_elements_by_xpath('//div[@id = "div_stats_standard_1631"] //tbody //td[@data-stat = "age"]')
lst_age2017_2018 = [x.text for x in element]

In [12]:
driver.get("https://fbref.com/en/squads/822bd0ba/2018-2019/Liverpool-Stats")
element = driver.find_elements_by_xpath('//div[@id = "div_stats_standard_1889"] //tbody //th[@data-append-csv]')
lst_players2018_2019 = [x.text for x in element]
element = driver.find_elements_by_xpath('//div[@id = "div_stats_standard_1889"] //tbody //td[@data-stat = "age"]')
lst_age2018_2019 = [x.text for x in element]

In [13]:
driver.get("https://fbref.com/en/squads/822bd0ba/2019-2020/Liverpool-Stats")
element = driver.find_elements_by_xpath('//div[@id = "div_stats_standard_3232"] //tbody //th[@data-append-csv]')
lst_players2019_2020 = [x.text for x in element]
element = driver.find_elements_by_xpath('//div[@id = "div_stats_standard_3232"] //tbody //td[@data-stat = "age"]')
lst_age2019_2020 = [x.text for x in element]

In [14]:
test = {"salah":{"2012/2013" : 26, "2013/2014" : 27},
        "mane" :{"2012/2013" : 28}
}

In [15]:
pd.DataFrame.from_dict(test).transpose()

       2012/2013  2013/2014
salah       26.0       27.0
mane        28.0        NaN

In [16]:
test2 = {"2012/2013" : {"Salah" : 25, "Gerrard" : 35},
         "2013/2014" : {"Salah" : 26, "Mané" : 28},
         "2014/2015" : {"Mané" : 29, "Firmino" : 27}
         }

In [17]:
pd.DataFrame.from_dict(test2)

         2012/2013  2013/2014  2014/2015
Salah         25.0       26.0        NaN
Gerrard       35.0        NaN        NaN
Mané           NaN       28.0       29.0
Firmino        NaN        NaN       27.0

## On crée des dictionnaires de dictionnaires pour stocker toutes les données

In [14]:
dicttest3 = {}

In [15]:
dicttest3['2012/2013'] = {}

In [16]:
for i in lst_players2012_2013 :
    for j in range(len(lst_age2012_2013)) :
        dicttest3["2012/2013"][lst_players2012_2013[j]] = lst_age2012_2013[j]

In [17]:
df2 = pd.DataFrame.from_dict(dicttest3)

In [18]:
df2

                  2012/2013
Andre Wisdom             19
Andy Carroll             23
Brad Jones               30
Conor Coady              19
Daniel Agger             27
Daniel Sturridge         22
Fabio Borini             21
Glen Johnson             27
Jamie Carragher          34
Joe Allen                22
Joe Cole                 30
Jonjo Shelvey            20
Jordan Henderson         22
Jordon Ibe               16
José Enrique             26
Lucas Leiva              25
Luis Suárez              25
Martin Kelly             22
Martin Škrtel            27
Nuri Şahin               23
Oussama Assaidi          23
Pepe Reina               29
Philippe Coutinho        20
Raheem Sterling          17
Sebastián Coates         21
Steven Gerrard           32
Stewart Downing          28
Suso                     18

In [19]:
dicttest3['2013/2014'] = {}
for i in lst_players2013_2014 :
    for j in range(len(lst_age2013_2014)) :
        dicttest3["2013/2014"][lst_players2013_2014[j]] = lst_age2013_2014[j]

In [20]:
df3 = pd.DataFrame.from_dict(dicttest3)

In [21]:
dicttest3['2014/2015'] = {}
for i in lst_players2014_2015 :
    for j in range(len(lst_age2014_2015)) :
        dicttest3["2014/2015"][lst_players2014_2015[j]] = lst_age2014_2015[j]

In [22]:
df4 = pd.DataFrame.from_dict(dicttest3)

In [23]:
dicttest3['2015/2016'] = {}
for i in lst_players2015_2016 :
    for j in range(len(lst_age2015_2016)) :
        dicttest3["2015/2016"][lst_players2015_2016[j]] = lst_age2015_2016[j]

In [24]:
df5 = pd.DataFrame.from_dict(dicttest3)

In [25]:
dicttest3['2016/2017'] = {}
for j in range(len(lst_age2016_2017)) :
    dicttest3["2016/2017"][lst_players2016_2017[j]] = lst_age2016_2017[j]

In [26]:
df6 = pd.DataFrame.from_dict(dicttest3)

In [27]:
dicttest3['2017/2018'] = {}
for j in range(len(lst_age2017_2018)) :
    dicttest3["2017/2018"][lst_players2017_2018[j]] = lst_age2017_2018[j]

In [28]:
df7 = pd.DataFrame.from_dict(dicttest3)

In [29]:
dicttest3['2018/2019'] = {}
for j in range(len(lst_age2018_2019)) :
    dicttest3["2018/2019"][lst_players2018_2019[j]] = lst_age2018_2019[j]

In [30]:
df8 = pd.DataFrame.from_dict(dicttest3)

In [31]:
dicttest3['2019/2020'] = {}
for j in range(len(lst_age2019_2020)) :
    dicttest3["2019/2020"][lst_players2019_2020[j]] = lst_age2019_2020[j]

In [32]:
df9 = pd.DataFrame.from_dict(dicttest3)

In [33]:
pd.set_option('display.max_rows', None)

In [34]:
df9

,2012/2013,2013/2014,2014/2015,2015/2016,2016/2017,2017/2018,2018/2019,2019/2020
Glen Johnson,27,28,29,NaN,NaN,NaN,NaN,NaN
Steven Gerrard,32,33,34,NaN,NaN,NaN,NaN,NaN
Daniel Agger,27,28,NaN,NaN,NaN,NaN,NaN,NaN
Luis Suárez,25,26,NaN,NaN,NaN,NaN,NaN,NaN
Pepe Reina,29,NaN,NaN,NaN,NaN,NaN,NaN,NaN
José Enrique,26,27,28,NaN,NaN,NaN,NaN,NaN
Stewart Downing,28,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Lucas Leiva,25,26,27,28,29,NaN,NaN,NaN
Martin Škrtel,27,28,29,30,NaN,NaN,NaN,NaN
Joe Allen,22,23,24,25,NaN,NaN,NaN,NaN
Raheem Sterling,17,18,19,NaN,NaN,NaN,NaN,NaN
Jordan Henderson,22,23,24,25,26,27,28,29
Jamie Carragher,34,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Andre Wisdom,19,20,NaN,NaN,NaN,NaN,NaN,NaN
Philippe Coutinho,20,21,22,23,24,25,NaN,NaN
Daniel Sturridge,22,23,24,25,26,27,28,NaN
Jonjo Shelvey,20,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Suso,18,NaN,20,NaN,NaN,NaN,NaN,NaN
Brad Jones,30,NaN,32,NaN,NaN,NaN,NaN,NaN
Nuri Şahin,23,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Fabio Borini,21,NaN,23,NaN,NaN,NaN,NaN,NaN
Martin Kelly,22,23,NaN,NaN,NaN,NaN,NaN,NaN
Sebastián Coates,21,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Jordon Ibe,16,17,18,19,NaN,NaN,NaN,NaN
Joe Cole,30,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Oussama Assaidi,23,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Andy Carroll,23,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Conor Coady,19,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Simon Mignolet,NaN,25,26,27,28,29,30,NaN
Jon Flanagan,NaN,20,NaN,22,NaN,24,NaN,NaN
Mamadou Sakho,NaN,23,24,25,NaN,NaN,NaN,NaN
Kolo Touré,NaN,32,33,34,NaN,NaN,NaN,NaN
Aly Cissokho,NaN,25,NaN,NaN,NaN,NaN,NaN,NaN
Victor Moses,NaN,22,NaN,NaN,NaN,NaN,NaN,NaN
Iago Aspas,NaN,25,NaN,NaN,NaN,NaN,NaN,NaN
Luis Alberto,NaN,20,NaN,NaN,NaN,NaN,NaN,NaN
Brad Smith,NaN,19,NaN,21,NaN,NaN,NaN,NaN
João Carlos Teixeira,NaN,20,NaN,22,NaN,NaN,NaN,NaN
Alberto Moreno,NaN,NaN,22,23,24,25,26,NaN
Emre Can,NaN,NaN,20,21,22,23,NaN,NaN
Adam Lallana,NaN,NaN,26,27,28,29,30,31
Dejan Lovren,NaN,NaN,25,26,27,28,29,30
Lazar Marković,NaN,NaN,20,NaN,NaN,NaN,NaN,NaN
Mario Balotelli,NaN,NaN,23,NaN,NaN,NaN,NaN,NaN
Javier Manquillo,NaN,NaN,20,NaN,NaN,NaN,NaN,NaN
Rickie Lambert,NaN,NaN,32,NaN,NaN,NaN,NaN,NaN
Jerome Sinclair,NaN,NaN,17,18,NaN,NaN,NaN,NaN
Cameron Brannagan,NaN,NaN,18,19,NaN,NaN,NaN,NaN
Sheyi Ojo,NaN,NaN,17,18,NaN,NaN,NaN,NaN
Jordan Rossiter,NaN,NaN,17,18,NaN,NaN,NaN,NaN
Danny Ward,NaN,NaN,21,22,NaN,24,NaN,NaN
Jordan Williams,NaN,NaN,18,NaN,NaN,NaN,NaN,NaN
Nathaniel Clyne,NaN,NaN,NaN,24,25,26,27,NaN
James Milner,NaN,NaN,NaN,29,30,31,32,33
Roberto Firmino,NaN,NaN,NaN,23,24,25,26,27
Christian Benteke,NaN,NaN,NaN,24,NaN,NaN,NaN,NaN
Divock Origi,NaN,NaN,NaN,20,21,22,23,24
Kevin Stewart,NaN,NaN,NaN,21,22,NaN,NaN,NaN
Joe Gomez,NaN,NaN,NaN,18,19,20,21,22
Danny Ings,NaN,NaN,NaN,23,NaN,25,NaN,NaN
Ádám Bogdán,NaN,NaN,NaN,27,NaN,NaN,NaN,NaN
Connor Randall,NaN,NaN,NaN,19,20,NaN,NaN,NaN
Pedro Chirivella,NaN,NaN,NaN,18,NaN,NaN,NaN,NaN
Sergi Canós,NaN,NaN,NaN,18,NaN,NaN,NaN,NaN
Steven Caulker,NaN,NaN,NaN,23,NaN,NaN,NaN,NaN
Ryan Fulton,NaN,NaN,NaN,19,NaN,NaN,NaN,NaN
Tiago Ilori,NaN,NaN,NaN,22,NaN,NaN,NaN,NaN
Georginio Wijnaldum,NaN,NaN,NaN,NaN,25,26,27,28
Joël Matip,NaN,NaN,NaN,NaN,24,25,26,27
Sadio Mané,NaN,NaN,NaN,NaN,24,25,26,27
Ragnar Klavan,NaN,NaN,NaN,NaN,30,31,NaN,NaN
Loris Karius,NaN,NaN,NaN,NaN,23,24,25,NaN
Trent Alexander-Arnold,NaN,NaN,NaN,NaN,17,18,19,20
Ben Woodburn,NaN,NaN,NaN,NaN,16,17,NaN,NaN
Marko Grujić,NaN,NaN,NaN,NaN,20,21,NaN,NaN
Ovie Ejaria,NaN,NaN,NaN,NaN,18,NaN,NaN,NaN
Rhian Brewster,NaN,NaN,NaN,NaN,16,NaN,NaN,19
Alex Manninger,NaN,NaN,NaN,NaN,39,NaN,NaN,NaN
Harry Wilson,NaN,NaN,NaN,NaN,19,NaN,NaN,NaN
Mohamed Salah,NaN,NaN,NaN,NaN,NaN,25,26,27
Andrew Robertson,NaN,NaN,NaN,NaN,NaN,23,24,25
Alex Oxlade-Chamberlain,NaN,NaN,NaN,NaN,NaN,23,24,25
Virgil van Dijk,NaN,NaN,NaN,NaN,NaN,26,27,28
Dominic Solanke,NaN,NaN,NaN,NaN,NaN,19,NaN,NaN
Rafael Camacho,NaN,NaN,NaN,NaN,NaN,17,18,NaN
Curtis Jones,NaN,NaN,NaN,NaN,NaN,16,17,18
Conor Masterson,NaN,NaN,NaN,NaN,NaN,18,NaN,NaN
Alisson,NaN,NaN,NaN,NaN,NaN,NaN,25,26
Fabinho,NaN,NaN,NaN,NaN,NaN,NaN,24,25
Naby Keïta,NaN,NaN,NaN,NaN,NaN,NaN,23,24
Xherdan Shaqiri,NaN,NaN,NaN,NaN,NaN,NaN,26,27
Adrián,NaN,NaN,NaN,NaN,NaN,NaN,NaN,32
Neco Williams,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18
Takumi Minamino,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24
Harvey Elliot,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16
Ki-Jana Hoever,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
Caoimhin Kelleher,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20
Andy Lonergan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35
Nathaniel Phillips,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22

In [35]:
driver.close()

In [36]:
df9.to_csv(r'C:\Users\jacky\Downloads\Work\ESILV\Projets\Liverpool\Test_Dev\age.csv', header = True, index = True)